services:
  app:
    build:
      context: .
      target: development
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./src:/app/src
      - ./fixtures:/app/fixtures:ro
      - ./public:/app/public:ro
