import { expect, test } from "@playwright/test";
import sharp from "sharp";
import { localSupabase } from "./helpers/local-supabase";
import { openWorkspaceSection } from "./helpers/workspace";

const local = localSupabase();
test("owner previews, uploads, publishes, updates and unpublishes a wedding", async ({ page, browser, baseURL }) => {
  test.setTimeout(90_000);
  const email = `publication-${crypto.randomUUID()}@example.test`;
  const password = crypto.randomUUID();
  const { data, error } = await local.admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (error || !data.user) throw new Error("Unable to create local test owner");
  const ownerId = data.user.id;
  const slug = `alex-${crypto.randomUUID()}`;
  const guest = await browser.newContext({ baseURL, viewport: page.viewportSize() });
  const guestPage = await guest.newPage();
  const photo = await sharp({ create: { width: 800, height: 600, channels: 3, background: "#738c79" } }).jpeg().toBuffer();
  const replacementPhoto = await sharp({ create: { width: 600, height: 900, channels: 3, background: "#a86464" } }).jpeg().toBuffer();
  let weddingId: string | undefined;
  const openSection = (name: string) => openWorkspaceSection(page, name);
  // The header status is shown from 768px; it must follow publish and unpublish without a manual reload.
  const expectHeaderStatus = async (status: string) => {
    if (test.info().project.name === "desktop") await expect(page.getByRole("banner").getByText(status, { exact: true })).toBeVisible();
  };
  try {
    await page.goto("/account/sign-in");
    await page.getByLabel("Email address").fill(email);
    await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await page.getByLabel("Your name", { exact: false }).fill("Alex");
    await page.locator('[name="second_name"]').fill("Morgan");
    await page.locator('[name="wedding_date"]').fill("2027-09-18");
    await page.locator('[name="location"]').fill("Bath, England");
    await page.getByRole("button", { name: "Save private draft" }).click();
    await expect(page.getByRole("status")).toContainText("private draft has been saved");
    weddingId = (await local.admin.from("weddings").select("id").eq("owner_id", ownerId).single()).data!.id;
    expect((await local.grantEntitlement(weddingId!, ownerId)).error).toBeNull();
    await openSection("Publish");
    await page.getByRole("link", { name: "Preview saved site" }).click();
    await expect(page.getByRole("heading", { name: "Save the Date" })).toBeVisible();
    expect((await guest.request.get("/dashboard/photo")).status()).toBe(404);
    await guestPage.goto("/dashboard/preview");
    await expect(guestPage).toHaveURL(/account\/sign-in/);
    await page.getByRole("link", { name: "Back to workspace" }).click();
    await openSection("Design");
    const cancelledChooser = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Choose photo" }).press("Enter");
    await (await cancelledChooser).setFiles([]);
    await expect(page.getByAltText("Your saved wedding photo")).toHaveCount(0);
    await page.getByLabel("Photo file").setInputFiles({ name: "photo.jpg", mimeType: "image/jpeg", buffer: photo });
    await expect(page.getByRole("status").filter({ hasText: "photo has been saved" })).toBeVisible();
    await expect(page.getByAltText("Your saved wedding photo")).toBeVisible();
    await expect(page.getByRole("button", { name: "Change photo" })).toBeFocused();
    await expect(page.getByRole("heading", { name: "Frame your photo" })).toBeVisible();
    const horizontal = page.locator('input[name="x"]');
    const vertical = page.locator('input[name="y"]');
    const zoom = page.locator('input[name="zoom"]');
    const mobileCrop = page.locator('.photo-framing-viewport[data-preview-size="mobile"]');
    await mobileCrop.scrollIntoViewIfNeeded();
    const cropBounds = await mobileCrop.boundingBox();
    if (!cropBounds) throw new Error("Framing preview is not visible");
    await page.mouse.move(cropBounds.x + cropBounds.width / 2, cropBounds.y + cropBounds.height / 2);
    await page.mouse.down();
    await page.mouse.move(cropBounds.x + cropBounds.width * 0.7, cropBounds.y + cropBounds.height * 0.7);
    await page.mouse.up();
    await expect(horizontal).not.toHaveValue("50");
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(horizontal).toHaveValue("50");
    await horizontal.focus();
    await page.keyboard.press("ArrowLeft");
    await expect(horizontal).toHaveValue("49");
    await page.getByRole("button", { name: "Cancel" }).click();
    await horizontal.fill("20");
    await vertical.fill("70");
    await zoom.fill("1.3");
    await page.getByRole("button", { name: "Save Save the Date framing" }).click();
    await expect(page.getByRole("status").filter({ hasText: "Photo framing saved" })).toBeVisible();
    await page.getByLabel("Details", { exact: true }).check();
    await horizontal.fill("80");
    await vertical.fill("30");
    await zoom.fill("1.2");
    await page.getByRole("button", { name: "Save Details framing" }).click();
    await expect(page.getByRole("status").filter({ hasText: "Photo framing saved" })).toBeVisible();
    await horizontal.fill("10");
    await page.getByRole("button", { name: "Reset" }).click();
    await expect(horizontal).toHaveValue("50");
    await expect(vertical).toHaveValue("60");
    await expect(zoom).toHaveValue("1");
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(horizontal).toHaveValue("80");
    expect((await local.admin.from("weddings").select("photo_framing").eq("id", weddingId).single()).data!.photo_framing).toEqual({
      minimal: { saveTheDate: { x: 20, y: 70, zoom: 1.3 }, details: { x: 80, y: 30, zoom: 1.2 } },
    });
    const firstPhotoSrc = await page.getByAltText("Your saved wedding photo").getAttribute("src");
    await page.getByLabel("Photo file").setInputFiles({ name: "photo.jpg", mimeType: "image/jpeg", buffer: photo });
    await expect(page.getByAltText("Your saved wedding photo")).not.toHaveAttribute("src", firstPhotoSrc!);
    expect((await page.request.get("/dashboard/photo")).status()).toBe(200);
    await page.getByLabel("Photo file").setInputFiles({ name: "fake.jpg", mimeType: "image/jpeg", buffer: Buffer.from("not a photo") });
    await expect(page.getByRole("main").getByRole("alert")).toContainText("couldn’t read that photo");
    await expect(page.getByAltText("Your saved wedding photo")).toBeVisible();
    await expect(page.getByRole("button", { name: "Change photo" })).toBeFocused();
    expect((await page.request.get("/dashboard/photo")).status()).toBe(200);
    expect((await local.admin.from("weddings").select("photo_framing").eq("id", weddingId).single()).data!.photo_framing).toEqual({});
    await page.getByLabel("Save the Date", { exact: true }).check();
    await page.locator('input[name="x"]').fill("20");
    await page.locator('input[name="y"]').fill("70");
    await page.locator('input[name="zoom"]').fill("1.3");
    await page.getByRole("button", { name: "Save Save the Date framing" }).click();
    await expect(page.getByRole("status").filter({ hasText: "Photo framing saved" })).toBeVisible();
    await page.getByLabel("Details", { exact: true }).check();
    await page.locator('input[name="x"]').fill("80");
    await page.locator('input[name="y"]').fill("30");
    await page.locator('input[name="zoom"]').fill("1.2");
    await page.getByRole("button", { name: "Save Details framing" }).click();
    await expect(page.getByRole("status").filter({ hasText: "Photo framing saved" })).toBeVisible();
    await page.getByRole("link", { name: /Change theme/ }).click();
    await page.getByRole("radio", { name: /Warm & Romantic/ }).check();
    await page.getByRole("button", { name: "Apply theme", exact: true }).click();
    await expect(page.getByRole("status")).toContainText("Theme saved to your private draft");
    await page.getByRole("link", { name: "Back to workspace" }).click();
    await openSection("Design");
    await expect(page.getByText("Editing Warm & Romantic")).toBeVisible();
    await expect(page.locator('input[name="x"]')).toHaveValue("50");
    await page.getByRole("link", { name: /Change theme/ }).click();
    await page.getByRole("radio", { name: /Modern Minimal/ }).check();
    await page.getByRole("button", { name: "Apply theme", exact: true }).click();
    await expect(page.getByRole("status")).toContainText("Theme saved to your private draft");
    await page.getByRole("link", { name: "Back to workspace" }).click();
    await openSection("Design");
    await expect(page.getByText("Editing Modern Minimal")).toBeVisible();
    await expect(page.locator('input[name="x"]')).toHaveValue("20");
    await openSection("Publish");
    await page.getByLabel("Your wedding URL").fill("dashboard");
    await page.getByRole("checkbox", { name: /I understand that anyone with the URL/ }).check();
    await page.getByRole("button", { name: "Publish site", exact: true }).click();
    await expect(page.getByRole("main").getByRole("alert").last()).toContainText("reserved");
    await page.getByLabel("Your wedding URL").fill(` ${slug.toUpperCase()} `);
    await page.screenshot({ path: test.info().outputPath("private-workspace.png"), fullPage: true });
    expect((await guest.request.get(`/${slug}`)).status()).toBe(404);
    await page.getByRole("button", { name: "Publish site", exact: true }).click();
    await expect(page.getByText("Your site is live for anyone with its URL.")).toBeVisible();
    await expectHeaderStatus("Published");
    await page.screenshot({ path: test.info().outputPath("published-workspace.png"), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const response = await guestPage.goto(`/${slug}`);
    expect(response!.status()).toBe(200);
    // Development Next.js uses mandatory revalidation; production dynamic pages use no-store.
    expect(response!.headers()["cache-control"]).toMatch(/no-store|no-cache, must-revalidate/);
    if (process.env.E2E_PRODUCTION) expect(response!.headers()["cache-control"]).toContain("no-store");
    await expect(guestPage.getByText("Bath, England", { exact: true })).toBeVisible();
    await expect(guestPage.locator(".wedding-photo img")).toHaveCSS("object-position", "20% 70%");
    await expect(guestPage.locator(".wedding-photo img")).toHaveCSS("transform", /matrix\(1\.3/);
    await expect(guestPage.locator('meta[name="robots"]')).toHaveAttribute("content", /noindex/);
    const asset = await guest.request.get(`/${slug}/photo`);
    expect(asset.status()).toBe(200);
    expect(asset.headers()["cache-control"]).toContain("no-store");
    expect(asset.headers()["content-type"]).toBe("image/webp");
    await guestPage.screenshot({ path: test.info().outputPath("published-guest.png"), fullPage: true });
    expect((await local.admin.from("weddings").update({ details_enabled: true, ceremony_venue: "The Orangery" }).eq("id", weddingId)).error).toBeNull();
    await guestPage.goto(`/${slug}/details`);
    await expect(guestPage.getByRole("heading", { name: "Wedding details" })).toBeVisible();
    await expect(guestPage.locator(".wedding-photo img")).toHaveCSS("object-position", "80% 30%");
    await expect(guestPage.locator(".wedding-photo img")).toHaveCSS("transform", /matrix\(1\.2/);
    await guestPage.goto(`/${slug}`);
    await openSection("Basics");
    await page.locator('[name="location"]').fill("Bristol, England");
    await page.getByRole("button", { name: "Save live changes" }).click();
    await expect(page.getByRole("status").filter({ hasText: "live wedding site has been updated" })).toBeVisible();
    await guestPage.reload();
    await expect(guestPage.getByText("Bristol, England", { exact: true })).toBeVisible();
    await openSection("Design");
    await page.getByLabel("Photo file").setInputFiles({ name: "replacement.jpg", mimeType: "image/jpeg", buffer: replacementPhoto });
    await expect(page.getByRole("status").filter({ hasText: "photo has been saved" })).toBeVisible();
    await page.reload();
    await expect(page.getByAltText("Your saved wedding photo")).toBeVisible();
    expect((await local.admin.from("weddings").select("photo_framing").eq("id", weddingId).single()).data!.photo_framing).toEqual({});
    await expect(page.locator('input[name="x"]')).toHaveValue("50");
    const ownerReplacement = await page.request.get("/dashboard/photo");
    const guestReplacement = await guest.request.get(`/${slug}/photo`);
    expect(ownerReplacement.status()).toBe(200);
    expect(guestReplacement.status()).toBe(200);
    const [ownerStats, guestStats] = await Promise.all([
      sharp(await ownerReplacement.body()).stats(),
      sharp(await guestReplacement.body()).stats(),
    ]);
    expect(ownerStats.channels[0].mean).toBeGreaterThan(ownerStats.channels[1].mean);
    expect(guestStats.channels[0].mean).toBeGreaterThan(guestStats.channels[1].mean);
    await openSection("Publish");
    await page.getByRole("button", { name: "Unpublish site" }).click();
    await expect(page.getByText("Your site is private until you publish it.")).toBeVisible();
    await expectHeaderStatus("Private draft");
    await expect(page.getByLabel("Your wedding URL")).toHaveAttribute("readonly", "");
    expect((await guest.request.get(`/${slug}`)).status()).toBe(404);
    expect((await guest.request.get(`/${slug}/photo`)).status()).toBe(404);
    expect((await page.request.get("/dashboard/photo")).status()).toBe(200);
    await openSection("Design");
    await page.getByLabel("Photo file").setInputFiles({ name: "oversized.jpg", mimeType: "image/jpeg", buffer: Buffer.alloc(7 * 1024 * 1024) });
    await expect(page.getByRole("alert").filter({ hasText: "over 5 MB" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Change photo" })).toBeFocused();
    await page.getByRole("button", { name: "Remove photo" }).click();
    await expect(page.getByRole("status").filter({ hasText: "photo has been removed" })).toBeVisible();
    expect((await page.request.get("/dashboard/photo")).status()).toBe(404);
    await openSection("Publish");
    await page.getByRole("checkbox", { name: /I understand that anyone with the URL/ }).check();
    await page.getByRole("button", { name: "Publish site", exact: true }).click();
    await expect(page.getByText("Your site is live for anyone with its URL.")).toBeVisible();
    await expectHeaderStatus("Published");
    expect((await guest.request.get(`/${slug}`)).status()).toBe(200);
    expect((await guest.request.get(`/${slug}/photo`)).status()).toBe(404);
  } finally {
    await guest.close();
    if (weddingId) {
      const files = await local.admin.storage.from("wedding-photos").list(weddingId);
      if (files.data?.length) await local.admin.storage.from("wedding-photos").remove(files.data.map((file) => `${weddingId}/${file.name}`));
    }
    await local.admin.auth.admin.deleteUser(ownerId);
  }
});
